apiVersion: v1
kind: Service
metadata:
  name: app
  creationTimestamp: null
  labels:
    app: app
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  selector:
    app: app
status:
  loadBalancer: {}