apiVersion: v1
kind: Service
metadata:
  name: db
  creationTimestamp: null
  labels:
    app: db
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: db
status:
  loadBalancer: {}